Traceback (most recent call last):
  File "train.py", line 844, in <module>
    loss_vals[loss] = loss_fns[loss](inp, out, target)
  File "train.py", line 526, in <lambda>
    lambda inp_, out_, target_: mmdfixsigma_fn(out_, target_,
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_101cuda/x86_64-centos7-gcc8-opt/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/srv/my_mmd.py", line 94, in forward
    kernels = MMD.gaussian_kernel(source, target, kernel_mul=self.kernel_mul, kernel_num=self.kernel_num, fix_sigma=sigma, one_sided_bandwidth=self.one_sided_bandwidth, l2dist_out=l2dist_out)
  File "/srv/my_mmd.py", line 37, in gaussian_kernel
    L2_distance = ((total0-total1)**2).sum(2)
RuntimeError: CUDA out of memory. Tried to allocate 2.50 GiB (GPU 0; 14.58 GiB total capacity; 12.56 GiB already allocated; 307.62 MiB free; 13.61 GiB reserved in total by PyTorch)
